// Mock Data for Alumni Bridge - Demo/Development
export const mockAlumni = [
  {
    id: '1',
    name: 'Rahul Sharma',
    company: 'Google',
    role: 'Senior SDE',
    avatar: '🧑‍💼',
    skills: ['Python', 'Go', 'Kubernetes'],
    graduation_year: 2018,
    department: 'CSE',
    location: 'Bangalore',
    willing_to_mentor: true,
  },
  {
    id: '2',
    name: 'Priya Desai',
    company: 'Microsoft',
    role: 'Product Manager',
    avatar: '👩‍💼',
    skills: ['Product Strategy', 'Data Analysis', 'SQL'],
    graduation_year: 2019,
    department: 'CSE',
    location: 'Hyderabad',
    willing_to_mentor: true,
  },
  {
    id: '3',
    name: 'Arjun Patel',
    company: 'Amazon',
    role: 'TPM',
    avatar: '👨‍💻',
    skills: ['Leadership', 'AWS', 'Technical Design'],
    graduation_year: 2017,
    department: 'ECE',
    location: 'Bangalore',
    willing_to_mentor: true,
  },
  {
    id: '4',
    name: 'Neha Gupta',
    company: 'Meta',
    role: 'Software Engineer',
    avatar: '👩‍💻',
    skills: ['React', 'JavaScript', 'GraphQL'],
    graduation_year: 2020,
    department: 'CSE',
    location: 'Remote',
    willing_to_mentor: true,
  },
  {
    id: '5',
    name: 'Vikram Singh',
    company: 'TechStartup Co',
    role: 'CTO & Co-founder',
    avatar: '🧑‍💼',
    skills: ['System Architecture', 'Fundraising', 'Leadership'],
    graduation_year: 2016,
    department: 'CSE',
    location: 'Bangalore',
    willing_to_mentor: true,
  },
];

export const mockJobs = [
  {
    id: '1',
    title: 'Senior Software Engineer',
    company: 'Google',
    location: 'Bangalore',
    type: 'full-time',
    salary: '₹35L - ₹50L',
    referral_available: true,
    posted_by: 'Rahul Sharma',
    description: 'We are looking for experienced SDE to join our Cloud Platform team.',
  },
  {
    id: '2',
    title: 'Product Manager',
    company: 'Microsoft',
    location: 'Hyderabad',
    type: 'full-time',
    salary: '₹25L - ₹40L',
    referral_available: true,
    posted_by: 'Priya Desai',
    description: 'Help shape the future of cloud products. Join our product team.',
  },
  {
    id: '3',
    title: 'Data Scientist',
    company: 'Amazon',
    location: 'Remote',
    type: 'full-time',
    salary: '₹30L - ₹45L',
    referral_available: false,
    posted_by: 'Arjun Patel',
    description: 'Apply ML to solve real customer problems at scale.',
  },
  {
    id: '4',
    title: 'Frontend Engineer Internship',
    company: 'TechStartup Co',
    location: 'Bangalore',
    type: 'internship',
    salary: '₹50K/month',
    referral_available: true,
    posted_by: 'Vikram Singh',
    description: '3-month internship. Perfect opportunity to learn React & TypeScript.',
  },
  {
    id: '5',
    title: 'Backend Engineer',
    company: 'Flipkart',
    location: 'Bangalore',
    type: 'full-time',
    salary: '₹20L - ₹35L',
    referral_available: true,
    posted_by: 'Rahul Sharma',
    description: 'Build scalable backend systems. 2+ years experience required.',
  },
  {
    id: '6',
    title: 'UI/UX Designer',
    company: 'Meta',
    location: 'Remote',
    type: 'full-time',
    salary: '₹22L - ₹38L',
    referral_available: false,
    posted_by: 'Neha Gupta',
    description: 'Design experiences for billions of users. Portfolio required.',
  },
];

export const mockEvents = [
  {
    id: '1',
    title: 'Cracking MAANG Interviews',
    type: 'webinar',
    date: new Date(2026, 1, 15),
    time: '8:00 PM',
    capacity: 150,
    registered: 120,
    description: 'Learn insider tips for MAANG interviews from Google & Microsoft engineers.',
  },
  {
    id: '2',
    title: 'Alumni Networking Mixer',
    type: 'meetup',
    date: new Date(2026, 1, 20),
    time: '6:00 PM',
    capacity: 100,
    registered: 85,
    description: 'Connect with alumni, make new friends, build your network.',
  },
  {
    id: '3',
    title: 'AI & ML Workshop',
    type: 'workshop',
    date: new Date(2026, 1, 22),
    time: '9:00 AM',
    capacity: 200,
    registered: 200,
    description: 'Hands-on workshop: Building ML models in production.',
  },
  {
    id: '4',
    title: 'Series A to Scale - Panel Discussion',
    type: 'panel',
    date: new Date(2026, 1, 28),
    time: '7:00 PM',
    capacity: 80,
    registered: 65,
    description: 'Founders share their journey from Series A to scaling. Q&A included.',
  },
  {
    id: '5',
    title: 'Resume Building 101',
    type: 'workshop',
    date: new Date(2026, 2, 5),
    time: '10:00 AM',
    capacity: 120,
    registered: 95,
    description: 'Create a resume that gets you interviews.',
  },
];

export const mockForumPosts = [
  {
    id: '1',
    title: 'Negotiating offer from Google - advice needed?',
    category: 'career',
    author: 'Rahul Sharma',
    avatar: '🧑‍💼',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    comments: 24,
    content: 'Just got an offer from Google for SDE role. How should I negotiate the package?',
  },
  {
    id: '2',
    title: 'Best way to approach system design problems?',
    category: 'technical',
    author: 'Arjun Patel',
    avatar: '👨‍💻',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    comments: 18,
    content: 'Struggling with system design interviews. Any resources or approach?',
  },
  {
    id: '3',
    title: 'How to evaluate startup equity offers?',
    category: 'career',
    author: 'Vikram Singh',
    avatar: '🧑‍💼',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    comments: 32,
    content: 'Got an offer with significant equity. How should I value it and negotiate?',
  },
  {
    id: '4',
    title: 'Startup vs Corporate - Which path to choose?',
    category: 'career',
    author: 'Priya Desai',
    avatar: '👩‍💼',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    comments: 28,
    content: 'Choosing between startup (Series B) and Google. Career advice appreciated!',
  },
  {
    id: '5',
    title: 'Most useful LeetCode patterns?',
    category: 'technical',
    author: 'Neha Gupta',
    avatar: '👩‍💻',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    comments: 15,
    content: 'Prepping for interviews. Which patterns helped you the most?',
  },
];

export const mockSuccessStories = [
  {
    id: '1',
    title: 'From Campus to Google in 6 Months',
    author: 'Rahul Sharma',
    type: 'career',
    image: '🚀',
    content: 'How I got my dream job at Google and the preparation strategy that worked.',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: '2',
    title: 'Founded a Series B Startup',
    author: 'Vikram Singh',
    type: 'startup',
    image: '💼',
    content: 'My journey from college to founding a successful startup and raising Series B funding.',
    date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: '3',
    title: 'Women in Tech - Breaking Barriers',
    author: 'Priya Desai',
    type: 'achievement',
    image: '👩‍💼',
    content: 'How I navigated tech as a woman and became a PM at Microsoft.',
    date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: '4',
    title: 'MBA Abroad - Worth It?',
    author: 'Neha Gupta',
    type: 'studies',
    image: '🎓',
    content: 'My experience doing MBA from a top university and its impact on my career.',
    date: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
  },
];

export const mockMentorshipRequests = [
  {
    id: '1',
    student: 'John Doe',
    mentor: 'Rahul Sharma',
    mentee_avatar: '👨‍🎓',
    mentor_avatar: '🧑‍💼',
    status: 'accepted',
    topic: 'Career growth in big tech',
  },
  {
    id: '2',
    student: 'Sarah Johnson',
    mentor: 'Priya Desai',
    mentee_avatar: '👩‍🎓',
    mentor_avatar: '👩‍💼',
    status: 'pending',
    topic: 'Product management fundamentals',
  },
  {
    id: '3',
    student: 'Alex Chen',
    mentor: 'Vikram Singh',
    mentee_avatar: '👨‍🎓',
    mentor_avatar: '🧑‍💼',
    status: 'accepted',
    topic: 'Startup journey and funding',
  },
];

export const mockDashboardStats = {
  verifiedAlumni: 145,
  openJobs: 28,
  internships: 8,
  upcomingEvents: 6,
  mentorshipRequests: 12,
  successStories: 34,
};
